CREATE DATABASE go;

USE go;

CREATE TABLE Poll (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Question NVARCHAR(255) NOT NULL
);

CREATE TABLE Optio (
    Id INT PRIMARY KEY IDENTITY(1,1),
    PollId INT,
    Text NVARCHAR(255) NOT NULL,
    Votes INT DEFAULT 0,
    FOREIGN KEY (PollId) REFERENCES Poll(Id)
);
